include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    sized_box_for_whitespace: false
    must_be_immutable: false
    non_constant_identifier_names: false
analyzer:
  errors:
    prefer_const_constructors: ignore
    must_be_immutable: ignore
